### ISSUE TITLE
combinging --serial and --fast-exit doesn't propagate error code

### ISSUE THREAD

**Issue by ilyaiqoqo** [hfour/wsrun#28] opened 2018-06-10 19:01 UTC
wsrun version 2.2.0

**Comment by ckknight** [comment] 2018-06-12 00:32
I am able to reproduce when I have one of my workspaces' `test` scripts failing:

`$(npm bin)/wsrun test --serial --exclude-missing --fast-exit && echo 'yay'` # exit code 0, 'yay'
`$(npm bin)/wsrun test --stages --exclude-missing --fast-exit && echo 'yay'` # exit code 1
`$(npm bin)/wsrun test --parallel --exclude-missing --fast-exit && echo 'yay'` # exit code 1

(There's a typo in the issue title, it's `--fast-exit`, not `--force-exit`)

**Comment by whoeverest** [comment] 2018-06-12 09:21
I'm having trouble reproducing the issue.

I tried making a project with 2 workspace packages, called `a` and `b` and setting their `build` commands to `exit 0` and `exit 1` respectively. I'm constantly getting exit code 0:

```
> cat packages/a/package.json 
{
  "name": "a",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": { "build": "exit 0" }
}
[11:10] whoeverest@whoeverest ~/playground/wsrun-propagate-error-test
> cat packages/b/package.json 
{
  "name": "b",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": { "build": "exit 1" }
}
```

The output:

```
> yarn wsrun build --stages --fast-exit; echo "error $?"
yarn run v1.6.0
$ /home/whoeverest/playground/wsrun-propagate-error-test/node_modules/.bin/wsrun build --stages --fast-exit
a
$ exit 0
b
$ exit 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`yarn build` failed with exit code 1
Stopping 2 active children
Aborted execution due to previous error
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error 1
[11:12] whoeverest@whoeverest ~/playground/wsrun-propagate-error-test
> yarn wsrun build --parallel --fast-exit; echo "error $?"
yarn run v1.6.0
$ /home/whoeverest/playground/wsrun-propagate-error-test/node_modules/.bin/wsrun build --parallel --fast-exit
b
$ exit 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
a
$ exit 0
`yarn build` failed with exit code 1
Stopping 2 active children
Aborted execution due to previous error
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error 1
[11:12] whoeverest@whoeverest ~/playground/wsrun-propagate-error-test
> yarn wsrun build --serial --fast-exit; echo "error $?"
yarn run v1.6.0
$ /home/whoeverest/playground/wsrun-propagate-error-test/node_modules/.bin/wsrun build --serial --fast-exit
a
$ exit 0
b
$ exit 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`yarn build` failed with exit code 1
Stopping 2 active children
Aborted execution due to previous error
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error 1
```

Any ideas what I'm doing differently?

**Comment by SketchingDev** [comment] 2018-08-23 13:03
I am able to recreate it when I have 3 workspaces, all exiting with non-zero.

```
> cat packages/a/package.json 
{
  "name": "a",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": { "build": "exit 1" }
}
> cat packages/b/package.json 
{
  "name": "b",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": { "build": "exit 1" }
}
> cat packages/c/package.json 
{
  "name": "c",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": { "build": "exit 1" }
}
```

```
> yarn wsrun build --serial --fast-exit; echo "error $?"
a
$ exit 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`yarn build` failed with exit code 1
Stopping 3 active children
Unhandled rejection TypeError: Cannot read property 'removeAllListeners' of undefined
    at children.forEach.ch (***/node_modules/wsrun/build/parallelshell.js:161:23)
    at Array.forEach (<anonymous>)
    at RunGraph.closeAll (***/node_modules/wsrun/build/parallelshell.js:160:27)
    at Promise.all.then.catch.err (***/node_modules/wsrun/build/parallelshell.js:303:54)
    at tryCatcher (***/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (***/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (***/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (***/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (***/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (***/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (***/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (***/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)

✨  Done in 0.71s.
error 0
```

**Comment by ckknight** [comment] 2019-01-23 20:58
This also appears to be an issue with `--stages`  a

**Comment by scottweber88** [comment] 2019-02-06 23:28
So what happens here is that the CmdProcesses are added to the .children array well before they are actually started. In serial+fast-exit, the whole thing is called off before they start. Hence exitCode doesn't correspond to any resolvable promise, and the the whole thing unravels [1], and the process exits before .checkResultsAndReport can be called, let alone process.exit(1).

Attempted resolution in https://github.com/whoeverest/wsrun/pull/42

**Comment by spion** [comment] 2019-03-08 17:36
Closing for now since #42 was merged - will reopen if needed

**Closed by spion** 2019-03-08 17:36 UTC
